version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "order-processing-task"
        LoadBalancerInfo:
          ContainerName: "order-processing-container"
          ContainerPort: 3000
        PlatformVersion: "LATEST"
Hooks:
  - BeforeInstall: "ecs-pre-hook"
  - AfterInstall: "ecs-post-hook"
  - AfterAllowTestTraffic: "ecs-test-hook"
  - BeforeAllowTraffic: "ecs-before-traffic-hook"
  - AfterAllowTraffic: "ecs-after-traffic-hook"
