version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing dependencies...
      - npm ci
      
  pre_build:
    commands:
      - echo Running tests with coverage...
      - npm run test:coverage
      
  build:
    commands:
      - echo Building application...
      - npm prune --production
      - echo Build completed on `date`
      
  post_build:
    commands:
      - echo Running smoke tests...
      - grep -q "Github" public/index.html
      - grep -q "Jenkins" public/index.html
      - echo All tests passed!


cache:
  paths:
    - 'node_modules/**/*'

artifacts:
  files:
    - '**/*'
    - '!node_modules/**/*'